version: '3.9'

services:

  postgres_db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # Doesn't matter since we're running locally
      POSTGRES_PASSWORD: example
      POSTGRES_DB: sw_db

volumes:
  postgres_data: