# Generated by Django 5.1.7 on 2025-03-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='omeworld',
            new_name='homeworld',
        ),
    ]
